### ISSUE TITLE
select only result

### ISSUE THREAD

**Issue by ildarkhasanshin** [colinta/SublimeCalculate#15]
now i enter into the editor and select all text
[select]2+2*2[/select]

call the calculate command and get selected all the text
[select]2+2*2 = 6[/select]

wish that were the end result
2+2*2 = [select]6[/select]

or the result is automatically copied to the clipboard (optional)

**Comment by colinta** [comment]
I'm happy to fix any bugs you find, but this sounds more like a feature request, which I normally don't do unless I would find it really useful.  If you want to implement it yourself (it wouldn't be hard!) I'd be happy to merge it in, though.  The Sublime Text API is *really* straightforward!
