### ISSUE TITLE
Hex calculations wrong

### ISSUE THREAD

**Issue by bitm0de** [colinta/SublimeCalculate#16]
When calculating 0xFF0000 by itself, the result is equivalent to 0xFF0 as it shows me 4080. Additionally, 0xFF0001 evaluates to 4081.

**Comment by bitm0de** [comment]
This line was causing the issue: 
`formula = re.sub(r'(?<![\d\.])0*(\d+)', r'\1', formula)`

**Comment by colinta** [comment]
That's a weird line; I removed it altogether.  I don't remember why I ever wanted to strip initial `000`s.  If it seems necessary I'll put it back with the regex you have there.  Thanks!  Fixed in 2.3.2

**Comment by bitm0de** [comment]
If leading 0’s aren’t removed equations like 002 + 003 fail. My regex added the requirement for it to be word boundary. Initially I commented it out as well thinking it wasn’t necessary.

**Comment by colinta** [comment]
Fair enough - it won't hurt to have it there.

Restored in 2.3.3
