### ISSUE TITLE
Float Point Precision Error

### ISSUE THREAD

**Issue by RCJacH** [colinta/SublimeCalculate#18]
There's currently float point precision error when doing calculation.
Example with random float:
2.4454+1.2424 = 3.6877999999999997 (should be 3.6878)
2.4454-1.2424 = 1.2029999999999998 (should be 1.203)
2.4454*1.2424 = 3.0381649599999996 (should be 3.03816496)

Would it be better to assign getcontext().prec from decimal library right before the calculate, with rounding=ROUND_05UP and precision equaling max digit if addition or subtraction, and product of digits after decimal point if it's multiplication?

**Comment by colinta** [comment]
How would you go about converting the math expression into `decimal` compatible python code?

Right now, the expression is just eval'd, with a handful of functions from `math` imported into as "local" to the `eval`.  Adding the `decimal` package would mean replacing numbers with `Decimal('...')` i.e. your example would need to become `Decimal('2.4454')+Decimal('1.2424')`.

Too much work for me!  If you want to contribute a pull request I'd love to see how you would implement this idea, but for me the complexity outweighs the benefit.
