### ISSUE TITLE
Any way to get average in selection?

### ISSUE THREAD

**Issue by 9840380** [colinta/SublimeCalculate#24]
Hi thanks for plugin!

Any way to get average in selection?

Thanks

**Comment by colinta** [comment]
There wasn't an easy way to do this... so I added one! Two, actually:

1. If you make some selections, you will now see `Sum: N Average N`
2. I added `mean()` function to the "calculate" command (select `mean(1,2,3)` and activate the command to replace or insert the calculation
3. I added a `CalculateMeanCommand`, which will use all the selections to calculate the mean, and insert it at an empty cursor

Available in 3.1.1❗

**Comment by 9840380** [comment]
Thanks, you genius!
